### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by ionutfechete** [r3s7/PayumBitPay#1]
The requested package r3s7/payumbitpay could not be found in any version, there may be a typo in the package name.

Any ideas on how to do this? Thanks a lot!

**Comment by frankirox** [comment]
Hello @IonutPerfectWeb, I think is because this package is not registered in packagist.org, so, you must need some additional lines in your composer.json inside of "repositories" example:

...,
"repositories": [
    {
       "type": "package",
        "package": {
             "name" : "r3s7/PayumBitPay",
             "version": "master",
             "source" : {
                                   "url": "https://github.com/r3s7/PayumBitPay.git",
                                   "type": "git",
                                   "reference": "master"
                             }
                         }
       }
],
...... and in your require the folliwing line will work now....

"require": {
......,
"r3s7/PayumBitPay" : "master",
.......
}

My best Regards,

**Comment by ionutfechete** [comment]
Got it to work, thanks anyway, hope this will help someone else! Thanks for quick response :+1: ,

**Comment by acorncom** [comment]
@IonutPerfectWeb You should also be able to use 

```
"require": {
    "r3s7/PayumBitPay" : "dev-master",
}
```

without needing the other stuff in your `composer.json` file

**Comment by ionutfechete** [comment]
@acorncom Nope, this outputs: "package not fund in any version "
